getwd()
setwd("C:/Users/Deepak SK/Desktop/3rd sem/datasets")
data=read.csv("CarPrice_Assignment (1).csv")
View(data)
head(data)
mean(data$enginesize)
mean(data$horsepower)
t.test(data$enginesize,mu=100)
t.test(data$horsepower,mu=100)
